# Generated by Django 6.0 on 2025-12-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecapsule', '0002_post_tag_comment_posttime_post_tags_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='local_file',
            field=models.FileField(blank=True, null=True, upload_to='downloads/'),
        ),
    ]
