# Generated by Django 6.0 on 2025-12-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecapsule', '0003_post_local_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='local_file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
