# Generated by Django 6.0 on 2025-12-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecapsule', '0004_alter_post_local_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_type',
            field=models.CharField(choices=[('video', 'Video'), ('photo', 'Photo'), ('image_album', 'Image Album'), ('none', 'None')], max_length=20),
        ),
    ]
